### ISSUE TITLE
Some customized vehicles cannot be put into service

### ISSUE THREAD

**Issue by JasonBourne1998** [YuqiHuai/SORA-SVL#7] opened 2022-06-24 03:00 UTC
Hi @YuqiHuai, Thank you very much for your local simulator. But when I use SVRA-SVL, some of my customized Apollo vehicles can not be put into use. I guess this is because some configuration vehicles are not put into assets? If possible, could you tell me the solution?
The following screenshot is the car in wise website that I want to use.
![2022-06-24 10-57-04 的屏幕截图](https://user-images.githubusercontent.com/51346614/175453249-bdbeaa4e-bbe4-4db3-8c80-16ad286b98d0.png)
The following screenshot is the output of the terminal.
![image](https://user-images.githubusercontent.com/51346614/175453287-614143da-e782-4590-961d-55221cce23b6.png)

**Comment by JasonBourne1998** [comment] 2022-06-25 09:33
@YuqiHuai  Hi, I guess this is because the vehicle Sensor Configurations do not include the ID. Could you please tell me if there is a way to add the Sensor Configuration on the localhost
![2022-06-25 17-32-46 的屏幕截图](https://user-images.githubusercontent.com/51346614/175767666-f2316000-84ea-4de8-bcf9-abda98ec713b.png)
?

**Comment by umdreamer** [comment] 2022-06-26 00:15
I encounter the same problem. Where is the sensor configuration located in the server?

**Comment by JasonBourne1998** [comment] 2022-06-26 02:02
> I encounter the same problem. Where is the sensor configuration located in the

**Comment by YuqiHuai** [comment] 2022-06-26 22:23
Hi all! Sorry I haven’t been checking issues over the past few days. 

I collected all publicly available sensor configurations a few weeks ago, so if yours isn’t in the dataset it need to be added.

Sensor configurations are located in the database, under collection vehicles, there are objects with ctype configuration. Those are specific vehicle configurations.

Amar from UVA was able to add custom sensor configuration, and I will add that feature ASAP.

**Comment by YuqiHuai** [comment] 2022-06-29 00:56
Closed as a duplicate of https://github.com/YuqiHuai/SORA-SVL/issues/8.

**Closed by YuqiHuai** 2022-06-29 00:56 UTC
